#!/bin/bash

mailing_list=$1
shift
subject=$@

mlist=$(echo $mailing_list | sed 's/[][]//g')%40lists.cloudfoundry.org
q=$(echo $subject | tr ' ' + | sed 's/[^a-zA-Z0-9_\.\+\-]//g')
search_url="https://lists.cloudfoundry.org/archives/search?mlist=${mlist}&q=${q}"

curl -s "https://www.pivotaltracker.com/services/v5/projects/1382120/stories" \
	-X POST \
	-H "X-TrackerToken: ${TRACKER_API_TOKEN}" \
	-H "Content-Type: application/json" \
	-d "{
		\"name\":\"${mailing_list} ${subject}\",
		\"description\":\"${search_url}\",
		\"story_type\":\"bug\",
		\"labels\":[\"issue\"]
	   }"
